// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4226.Huskies;

import org.usfirst.frc4226.Huskies.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc4226.Huskies.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton joystickButton1;
    public JoystickButton joystickButton2;
    public JoystickButton joystickButton3;
    public Joystick joystick2;
    public Joystick joystick1;
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton joystick2_X;
    public JoystickButton joystick2_Y;
    public JoystickButton joystick2_RBump;
    public JoystickButton joystick2_LBump;

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick1 = new Joystick(0);
        
        joystick2 = new Joystick(1);
        
        joystickButton3 = new JoystickButton(joystick2, 1);
        joystickButton3.whileHeld(new ClimbCmd());
        joystickButton2 = new JoystickButton(joystick2, 5);
        joystickButton2.whileHeld(new SolenoidClose());
        joystickButton1 = new JoystickButton(joystick2, 5);
        joystickButton1.whileHeld(new SolenoidOpen());


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Solenoid Open", new SolenoidOpen());
        SmartDashboard.putData("Solenoid Close", new SolenoidClose());
        SmartDashboard.putData("ClimbCmd", new ClimbCmd());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        joystick2_X = new JoystickButton(joystick2, 3);
        joystick2_X.whenReleased(new Auto_01_Peg_Center());
        
        joystick2_RBump = new JoystickButton(joystick2,6);
        joystick2_RBump.whenPressed(new SolenoidOpen());
        
        joystick2_LBump = new JoystickButton(joystick2,5);
        joystick2_LBump.whenPressed(new SolenoidClose());
        //joystick2_Y = new JoystickButton(joystick2, 4);
        //joystick2_Y.whenReleased(new Drive_Turn_To_Setpoint(0.0));
        
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick2() {
        return joystick2;
    }

    public Joystick getJoystick1() {
        return joystick1;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

